#!/bin/bash
RED="\e[31m"
GREEN="\e[32m"
ENDCOLOR="\e[0m"

#################################################
#Credit To Phantomiman (SAMI), Sharing with love .
#################################################

echo "
  ______                      _  _   _____  _   _  _____ 
 |  ____|                    | || | |  __ \| \ | |/ ____|
 | |__   _ __  _   _ _ __ ___| || |_| |  | |  \| | (___  
 |  __| | '_ \| | | | '_ ` _ |__   _| |  | | . ` |\___ \ 
 | |____| | | | |_| | | | | | | | | | |__| | |\  |____) |
 |______|_| |_|\__,_|_| |_| |_| |_| |_____/|_| \_|_____/ 
                                                        "
echo -e "${RED}This tool made by Phantomiman for educational purposes only V1"${ENDCOLOR}"
_________________________________________________________"
echo -e "${RED}Choose defualt recursive wordlists [*] OR Spesific list[1..5] "${ENDCOLOR}
read selection
echo  "[+] Please metion the destination domain, EX: domain.com"
read choose
echo -e "\e[32mNS Records ========================================\e[0m"
host -t ns  $choose
echo -e "\e[32mMX Records ========================================\e[0m"
host -t mx  $choose
echo " ==========================================================="
echo -e "${RED}[*] Scanning $choose for A records"${ENDCOLOR}
for ip in $(cat $selection.txt); do host $ip.$choose;done |grep -v "not found"
echo -e "${RED}[* PTR SCANNER] Provide 3 octets of the IP address to scan PTR"${ENDCOLOR}
read ipptr
for ip in $(seq 100 190);do host $ipptr.$ip;done |grep -v "not found"
